In [2]:
import pandas as pd
from pathlib import Path
import os
import numpy as np
import scipy as sci

import sys

In [3]:
hdf = pd.HDFStore("../../data/data_raw.h5", mode="r")
keys = hdf.keys()

In [4]:
_A_csv = pd.read_csv("../../data/LG JH3 Cell characterization planning sheet.csv")
_B_csv = pd.read_csv("../../data/Nissan Leaf Cell characterization planning sheet.csv")
_C_csv = pd.read_csv("../../data/Ford Fusion Cell characterization planning sheet .csv")
_D_csv = pd.read_csv("../../data/A123 M1 Cell characterization planning sheet.csv")

In [5]:
A_csv = _A_csv[_A_csv['Step Number'].notna()].reset_index(drop=True).set_index('Step Number')
B_csv = _B_csv[_B_csv['Step Number'].notna()].reset_index(drop=True).set_index('Step Number')
C_csv = _C_csv[_C_csv['Step Number'].notna()].reset_index(drop=True).set_index('Step Number')
D_csv = _D_csv[_D_csv['Step Number'].notna()].reset_index(drop=True).set_index('Step Number')

In [6]:
key = keys[0]
df = hdf.get(key)
df

,"Total Time, S",Cycle,Loop Counter #1,Loop Counter #2,Loop Counter #3,Step,"Step Time, S","Current, A","Voltage, V","Power, W","Amp-Hours, AH","Watt-Hours, WH","Temperature A1, °C",Mode,Real Time,Data Acquisition Flag,Segment Description,"Segment Time, S",SOC
0,1.0,1,1,1,1,1,1.0,0.0,3.152,0.0,0.0,0.0,29.5,REST,6/25/2024 6:05:04 AM,,nan,NaN,NaN
1,2.0,1,1,1,1,1,2.0,0.0,3.152,0.0,0.0,0.0,30.0,REST,6/25/2024 6:05:05 AM,,nan,NaN,NaN
2,3.0,1,1,1,1,1,3.0,0.0,3.152,0.0,0.0,0.0,29.5,REST,6/25/2024 6:05:06 AM,,nan,NaN,NaN
3,4.0,1,1,1,1,1,4.0,0.0,3.152,0.0,0.0,0.0,30.0,REST,6/25/2024 6:05:07 AM,,nan,NaN,NaN
4,5.0,1,1,1,1,1,5.0,0.0,3.152,0.0,0.0,0.0,30.0,REST,6/25/2024 6:05:08 AM,,nan,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
326358,493005.8,1,1,1,1,53,1760.0,0.0,2.883,0.0,0.0,0.0,30.0,REST,6/30/2024 11:17:44 PM,,nan,NaN,NaN
326359,493015.8,1,1,1,1,53,1770.0,0.0,2.883,0.0,0.0,0.0,30.0,REST,6/30/2024 11:17:54 PM,,nan,NaN,NaN
326360,493025.8,1,1,1,1,53,1780.0,0.0,2.883,0.0,0.0,0.0,30.0,REST,6/30/2024 11:18:04 PM,,nan,NaN,NaN
326361,493035.8,1,1,1,1,53,1790.0,0.0,2.883,0.0,0.0,0.0,30.0,REST,6/30/2024 11:18:14 PM,,nan,NaN,NaN
326362,493045.8,1,1,1,1,53,1800.0,0.0,2.883,0.0,0.0,0.0,30.0,REST,6/30/2024 11:18:24 PM,Q,nan,NaN,NaN

In [7]:
# add columns from csv based on step number

columns_of_interest = [
    "Control Current",
    "Control Voltage",
    "Control Power",
    "Limit Current",
    "Limit Voltage",
    "Limit Power",
    "Limit Inequality",
    "Limit Time",
]

for step in df['Step'].unique():
    if step in A_csv.index:
        for col in columns_of_interest:
            df.loc[df['Step'] == step, col] = A_csv.loc[step, col]

In [8]:
df[df['Step'] == 84]

,"Total Time, S",Cycle,Loop Counter #1,Loop Counter #2,Loop Counter #3,Step,"Step Time, S","Current, A","Voltage, V","Power, W",...,"Segment Time, S",SOC,Control Current,Control Voltage,Control Power,Limit Current,Limit Voltage,Limit Power,Limit Inequality,Limit Time
112318,208673.9,1,1,1,1,84,0.1,-4.6,2.856,-13.1,...,32.0,0.005269,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
112319,208674.0,1,1,1,1,84,0.2,-4.6,2.855,-13.1,...,32.1,0.005217,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
112320,208674.1,1,1,1,1,84,0.3,-4.6,2.854,-13.1,...,32.2,0.005165,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
112321,208674.2,1,1,1,1,84,0.4,-4.6,2.853,-13.1,...,32.3,0.005113,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
112322,208674.3,1,1,1,1,84,0.5,-4.6,2.852,-13.1,...,32.4,0.005061,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176510,281437.4,1,1,1,1,84,3.6,-4.6,3.288,-15.1,...,35.5,0.963994,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
176511,281437.5,1,1,1,1,84,3.7,-4.6,3.288,-15.1,...,35.6,0.963942,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
176512,281437.6,1,1,1,1,84,3.8,-4.6,3.288,-15.1,...,35.7,0.963890,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
176513,281437.7,1,1,1,1,84,3.9,-4.6,3.288,-15.1,...,35.8,0.963839,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0
176514,281437.8,1,1,1,1,84,4.0,-4.6,3.288,-15.1,...,35.9,0.963787,-128.0,3.0,NaN,NaN,NaN,NaN,>,4.0

In [9]:
key[1:]

'D/data_240624_ReCellML_A123_Cell01_charac_30C'